name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-and-release:
    name: Build and Release
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Build plugin file
        uses: AdamCarballo/streamdeck-distribution-tool@v1.0.2
        with:
          input: com.zakini.card-dealer.sdPlugin
          working-directory: packages/stream-deck-plugin
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: |
            packages/app/dist/card-dealer.html
            packages/stream-deck-plugin/com.zakini.card-dealer.streamDeckPlugin
